title: Stay Happy
theme: minima
author: GitHub User
email: palakgupta0503@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hope everyone reading this have a good year ahead!

# social links
twitter_username: palakgupta0503 # DO NOT include the @ character, or else the build will fail!
github_username:  palakgupta0503 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
